module.exports = {
  QUICK_START: {
    ROUTE_NAME: 'quick_start',
    HOME: '/home',
    HEADERS: '/modules/headers',
    FOOTERS: {
      BASIC: '/modules/footers/basic',
      CORPORATE: '/modules/footers/corporate',
    },
    MARQUEES: {
      BASIC: '/modules/marquees/basic',
      CTA: '/modules/marquees/cta',
      EXTENDED: '/modules/marquees/extended',
      ILLUSTRATION: '/modules/marquees/illustration',
      IMAGE: '/modules/marquees/image',
      STANDAR: '/modules/marquees/standar',
      TEXT: '/modules/marquees/text',
      TEXTIMAGE: '/modules/marquees/textImage',
    },
    BUTTONS: '/components/buttons',
    ALERTS: '/components/alerts',
    ICONS: '/components/icons',
    LINKS: '/components/links',
    TEXT: '/components/text',
    CARDS: '/components/cards',
    PRODUCT_CARDS: '/components/productCards',
    INTERACTION: '/components/interaction',
    GRIDCELLS: '/components/gridCells',
    MICROILLUSTRATIONS: '/components/microillustrations',
    ILLUSTRATIONS: '/components/illustrations',
    SCENES: '/components/scenes',
  },
}
