module.exports = {
  QUICK_START: {
    ROUTE_NAME: 'quick_start',
    HOME: '/home',
    HEADERS: '/modules/headers',
    FEATURED_CONTENT: '/modules/featuredContents',
    FOOTERS: {
      BASIC: '/modules/footers/basic',
      STANDARD: '/modules/footers/standard',
      CORPORATE: '/modules/footers/corporate',
      NEWSLETTER: '/modules/footers/newsletter',
    },
    BASIC_CONTENTS: '/modules/basicContents',
    ICON_DESCRIPTION: '/modules/iconsDescription',
    BUTTONS: '/components/buttons',
    ALERTS: '/components/alerts',
    ICONS: '/components/icons',
    LINKS: '/components/links',
    TEXTS: '/components/texts',
    CARDS: '/components/cards',
    PRODUCT_CARDS: '/components/productCards',
    INTERACTION: '/components/interaction',
    GRID_CELLS: '/components/gridCells',
    FORMS: '/components/forms',
    MICROILLUSTRATIONS: '/components/microillustrations',
    ILLUSTRATIONS: '/components/illustrations',
    SCENES: '/components/scenes',
    ICON_DESCRIPTION_COMPONENT: '/components/iconsDescription'
  },
}
