module.exports = {
  QUICK_START: {
    ROUTE_NAME: 'quick_start',
    HOME: '/home',
    HEADERS: '/modules/headers',
    FEATURED_CARDS: '/modules/featureCards',
    STATISTICS: '/modules/statistics',
    CATEGORIES_MENU: '/modules/categories-menu',
    SERVICE_GRIDS: '/modules/serviceGrids',
    TEAM_GRIDS: '/modules/teamGrids',
    CONTACTS: '/modules/contacts',
    SERVICES: '/modules/services',
    FOOTERS: {
      BASIC: '/modules/footers/basic',
      STANDARD: '/modules/footers/standard',
      CORPORATE: '/modules/footers/corporate',
      NEWSLETTER: '/modules/footers/newsletter',
    },
    ICON_DESCRIPTION: '/modules/iconsDescription',
    ICONS_SOCIAL: '/modules/iconSocial',
    CTA: '/modules/cta',
    CONTACT_BAR: '/modules/contactBar',
    MARQUEES: {
      BASIC: '/modules/marquees/basic',
      CTA: '/modules/marquees/cta',
      EXTENDED: '/modules/marquees/extended',
      ILLUSTRATION: '/modules/marquees/illustration',
      IMAGE: '/modules/marquees/image',
      STANDAR: '/modules/marquees/standar',
      TEXTIMAGE: '/modules/marquees/textImage',
    },
    BASIC_CONTENTS: '/modules/basicContents',
    FAQS: '/modules/faqs',
    ICON_SERVICES: '/modules/iconServices',
    BUSINESS_CASES: '/modules/businessCases',
    PORTFOLIOS:{
      BASIC: '/modules/portfolios/basic',
      DECOMPOSED: '/modules/portfolio/decomposed'
    },
    LOGINS: '/modules/login',
    BRANDS: '/modules/brands',
    BASIC_GRID: '/modules/basicGrids',
    TESTIMONIALS: '/modules/testimonials',
    PRODUCT_GRIDS: '/modules/productCards',
    SEARCHERS: '/modules/searchers',
    PRICES: '/modules/prices',
    BUTTONS: '/components/buttons',
    ALERTS: '/components/alerts',
    ICONS: '/components/icons',
    LINKS: '/components/links',
    TEXTS: '/components/texts',
    CARDS: '/components/cards',
    PRODUCT_CARDS: '/components/productCards',
    INTERACTION: '/components/interaction',
    GRID_CELLS: '/components/gridCells',
    FORMS: '/components/forms',
    MICROILLUSTRATIONS: '/components/microillustrations',
    ILLUSTRATIONS: '/components/illustrations',
    SCENES: '/components/scenes',
    ICON_DESCRIPTION_COMPONENT: '/components/iconsDescription'
  },

}
