module.exports = {
  DEMOS: {
    ROUTE_NAME: 'demos',
    STARTUP: '/demos/startup',
    DESIGN_STUDIO: '/demos/design-studio',
    BRANDING: '/demos/branding',
    DIGITAL_PRODUCT: '/demos/digital-product',
    CREATIVE_STUDIO: '/demos/creative-studio',
    FREELANCE: '/demos/freelance',
    DEVELOPMENT_STUDIO: '/demos/development-studio',
    CORPORATE: '/demos/corporate',
    CREATIVE_AGENCY: '/demos/creative-agency',
    FURNITURE: '/demos/furniture',
    MODERN_SHOP: '/demos/modern-shop',
    CLASSIC_SHOP: '/demos/classic-shop',
    LEGAL: '/demos/legal',
    FITNESS: '/demos/fitness',
    ARCHITECTURE: '/demos/architecture',
    MARKETPLACE: '/demos/marketplace',
    RESTAURANT: '/demos/restaurant',
  },
};
