module.exports = {
  DEMOS: {
    ROUTE_NAME: 'demos',
    STARTUP: '/demos/startup',
    HOME2: '/demos/home-cta',
    BRANDING: '/demos/branding',
    DIGITAL_PRODUCT: '/demos/digital-product',
    CREATIVE_STUDIO: '/demos/creative-studio',
    FREELANCE: '/demos/freelance',
    DEVELOPMENT_STUDIO: '/demos/development-studio',
    CORPORATIVE: '/demos/corporative',
    CREATIVE_AGENCY: '/demos/creative-agency',
    MODERN_SHOP: '/demos/modern-shop',
    CLASSIC_SHOP: '/demos/classic-shop',
    LEGAL: '/demos/legal',
    FITNESS: '/demos/fitness',
  },
  PAGES: {
    ABOUT_US: 'pages/about_us',
    ABOUT_ME: 'pages/about_me',
    ABOUT_B_SYSTEM: 'pages/about_b_system',
    HOW_WE_WORK: 'pages/how_we_work',
    OUR_SERVICES: 'pages/our_services',
    WHAT_WE_OFFER: 'pages/what_we_offer',
    TEAM_CLASSIC: 'pages/team_classic',
    TEAM_MODERN: 'pages/team_modern',
    PRODUCT_CLASSIC: 'pages/product_classic',
    PRODUCT_MODERN: 'pages/product_modern',
    PORTFOLIO_CLASSIC_GRID: 'pages/portfolio_classic_grid',
    PORTFOLIO_CLASSIC_WIDE: 'pages/portfolio_classic_wide',
    PORTFOLIO_GALLERY_WIDE: 'pages/portfolio_gallery_wide',
    PORTFOLIO_MASONRY: 'pages/portfolio_masonry',
    PORTFOLIO_MASONRY_PATH: 'pages/portfolio_masonry_path',
    PORTFOLIO_PATTERN: 'pages/product_pattern',
    SERVICES_PORTFOLIO: 'pages/services_portfolio',
    CUSTOMER_SUPPORT: 'pages/customer_support',
    TESTIMONIALS: 'pages/testimonials',
    CONTACT_CLASSIC: 'pages/contact_classic',
    PRODUCT_PACKS: 'pages/product_packs',
  },
};
